### ISSUE TITLE
Performance drop on v4.22.0 onwards

### ISSUE THREAD

**Issue by tommeier** [appium/appium-uiautomator2-server#426]
Hi,

I'm unsure of cause yet, but we're seeing significant performance drops for v4.22.0 onwards. We have a pretty significant suite that generally averages around ~31 minutes per build, with v4.22.0 this increases to ~45 minutes.

Something in this diff:
https://github.com/appium/appium-uiautomator2-server/compare/v4.21.1...v4.22.0

I've tested on v4.22.1 also and the issue persists.

Locking our builds to v4.21.1 solves performance issues.

**Comment by mykola-mokhnach** [comment]
Most likely https://github.com/appium/appium-uiautomator2-server/pull/422 did affect the performance in your case. 

I would try to play with `waitForIdleTimeout` and/or `waitForSelectorTimeout` settings to reduce possible delays in elements location. The other solution could be to make sure the application under test does not hog the UI thread for too long

These are only assumptions though. We'd need more detailed information/comparison about what and where takes too mach time in order to apply any fixes.

**Comment by tommeier** [comment]
@mykola-mokhnach yup sure, no change with timeout tweaks, this is the difference in performance before/after/reverted on our average times:

![image](https://user-images.githubusercontent.com/19973/118901671-3789c080-b957-11eb-9d3b-bd1cb71e900e.png)

Also seeing _many_ errors of unable to find elements but work, albeit slowly, on retries

**Comment by mykola-mokhnach** [comment]
Sorry, but I need more boring details. The chart above does not help much

**Comment by tommeier** [comment]
Fixed https://github.com/appium/appium/issues/15829#issuecomment-917626939
