### ISSUE TITLE
UiAutomator2 driver is unable to detect web elements in webview after updates in web app

### ISSUE THREAD

**Issue by sale7rawan** [appium/appium-uiautomator2-server#538]
I have a Hybrid Android app and I use appium to interact with it. Elements used to be detected from webviews but after web app made some updates, the driver no longer detects elements inside webview.
All updates made on the web app are not related to how elements can be inspected. Evidently so, when trying to use chrome inspector, elements can be found as web elements easily.
The issue is with how the UiAutomator2 driver is interpreting the web elements as mobile elements.

**Comment by sale7rawan** [comment]
The thing is that we have both an Android and an iOS app that both view the same webview.
When using Appium inspector to inspect elements in iOS app, all elements in webview are intercepted and have their elements located.
But that's not the case when inspecting the Android app. Only the <android.webkit.WebView> element is found and nohing inside it.

**Comment by KazuCocoa** [comment]
It sounds like AccessibilityNodeInfo related in native app context, you may need to report it to Google if needed.

NATIVE_APP context in UIA2 depends on https://developer.android.com/reference/android/view/accessibility/AccessibilityNodeInfo . It could show WebView element such as https://developer.android.com/reference/android/webkit/WebView in its NATIVE_APP context, but it basically depends on how Android handle them.

For iOS, if you haven't changed the context, then it was because XCTest framework (by Apple, Appium depends on that) parsed Web element. Thus the difference was how Android (by Google) handles the web content vs how XCTest (by Apple) handles the web content.

As Appium, web view related should be in WEBVIEW context since NATIVE_APP context basically depends on OS. The web view result could be different than what chromedriver (for android for example) shows.
e.g. https://github.com/appium/appium-uiautomator2-driver?tab=readme-ov-file#hybrid-mode

**Comment by KazuCocoa** [comment]
Please check WebView stuff in the WebView context (Appium's expected usage for WebView content), otherwise it looks like Android's accessibility/AccessibilityNodeInfo related. Then, nothing can do in Appium side
